# Generated by Django 4.1.1 on 2022-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_banner_active_banner_created_banner_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfos',
            name='year',
            field=models.PositiveIntegerField(default=2022),
            preserve_default=False,
        ),
    ]
