# Generated by Django 4.1.1 on 2022-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_banner_slide_1_banner_slide_2_banner_slide_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherbanner',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteinfos',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
