# Generated by Django 4.1.1 on 2022-09-28 11:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'City',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'State',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'StatusProperty',
                'verbose_name_plural': 'StatusProperties',
                'db_table': 'StatusProperty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubmitProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_first', models.FileField(upload_to='image_first')),
                ('name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CI')),
                ('description', tinymce.models.HTMLField()),
                ('bed_numbers', models.PositiveBigIntegerField(blank=True, null=True)),
                ('bath_numbers', models.PositiveBigIntegerField(blank=True, null=True)),
                ('area_numbers', models.PositiveBigIntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='img1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='img2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='img3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='img4')),
                ('videos', models.URLField(blank=True, null=True)),
                ('videos2', models.ImageField(blank=True, null=True, upload_to='videos2')),
                ('accept_condition', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_city', to='service.city')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_status', to='service.statusproperty')),
            ],
            options={
                'verbose_name': 'SubmitProperty',
                'verbose_name_plural': 'SubmitProperties',
                'db_table': 'SubmitProperty',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properti_state', to='service.state'),
        ),
    ]
