# Generated by Django 4.1.1 on 2022-09-29 10:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitproperty',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
