# Generated by Django 4.1.1 on 2022-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_submitproperty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitproperty',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
