# Generated by Django 4.1.1 on 2022-09-30 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_submitproperty_user_property_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('built_in', models.PositiveIntegerField(blank=True, null=True)),
                ('water_front', models.CharField(blank=True, max_length=3, null=True)),
                ('accessible_vehicule', models.CharField(blank=True, max_length=3, null=True)),
                ('child_bredroom', models.CharField(blank=True, max_length=3, null=True)),
                ('desc_water_front', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'AdditonalDetail',
                'verbose_name_plural': 'AdditonalDetails',
                'db_table': 'AdditonalDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AreaProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('interval', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BathNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('interval', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('interval', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CategoryProperty',
                'verbose_name_plural': 'CategoryProerties',
                'db_table': 'CategoryProperty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GarageNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('interval', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('interval', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='city',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statusproperty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statusproperty',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statusproperty',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='cheminer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='jadin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='piscine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='sortie_secours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='terrain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='additional_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_additionaldetails', to='service.additonaldetails'),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='category_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_category', to='service.categoryproperty'),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='garage_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_Garage', to='service.garagenumber'),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_price', to='service.pricerange'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='area_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_area', to='service.areaproperty'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='bath_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_bath', to='service.bathnumber'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='bed_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_bed', to='service.bednumber'),
        ),
    ]
