# Generated by Django 4.1.1 on 2022-10-04 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_additonaldetails_areaproperty_bathnumber_bednumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRangeMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('interval', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='PriceRange',
            new_name='PriceRangeMax',
        ),
    ]
