# Generated by Django 4.1.1 on 2022-10-04 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_pricerangemin_rename_pricerange_pricerangemax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitproperty',
            old_name='jadin',
            new_name='jardin',
        ),
        migrations.AlterField(
            model_name='additonaldetails',
            name='desc_water_front',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
