# Generated by Django 4.1.1 on 2022-10-04 17:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_jadin_submitproperty_jardin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitproperty',
            name='additional_detail',
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='accessible_vehicule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='built_in',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='child_bredroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='desc_water_front',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitproperty',
            name='water_front',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AdditonalDetails',
        ),
    ]
