# Generated by Django 4.1.1 on 2022-10-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0008_remove_submitproperty_additional_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='area_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_numbers', to='service.areaproperty'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='bath_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bath_numbers', to='service.bathnumber'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='bed_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_numbers', to='service.bednumber'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='category_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_property', to='service.categoryproperty'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='service.city'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='garage_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_number', to='service.garagenumber'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_range', to='service.pricerangemin'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='service.statusproperty'),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='user_property_submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit_prperty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='built_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.builtin'),
        ),
    ]
