# Generated by Django 4.1.1 on 2022-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_builtin_alter_submitproperty_area_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproperty',
            name='desc_parking',
            field=models.CharField(default='2 places ou plus, Parking couvert, Service de voiturier', max_length=50),
            preserve_default=False,
        ),
    ]
