# Generated by Django 4.1.1 on 2022-10-07 14:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_submitproperty_desc_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproperty',
            name='vue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='desc_parking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='desc_water_front',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True),
        ),
    ]
