# Generated by Django 4.1.1 on 2022-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_submitproperty_vue_alter_submitproperty_desc_parking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitproperty',
            name='videos2',
            field=models.FileField(blank=True, null=True, upload_to='videos2'),
        ),
    ]
