# Generated by Django 4.1.1 on 2022-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_submitproperty_desc_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaproperty',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bathnumber',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bednumber',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='builtin',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoryproperty',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='garagenumber',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricerangemax',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricerangemin',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statusproperty',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submitproperty',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
