# Generated by Django 4.1.1 on 2022-10-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_emailvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvisitor',
            name='emailvisitor',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
