# Generated by Django 4.1.1 on 2022-10-12 14:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_emailvisitor_emailvisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvisitor',
            name='phonevisitor',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CI'),
        ),
    ]
