# Generated by Django 4.1.1 on 2022-10-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_emailvisitor_phonevisitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
    ]
