# Generated by Django 4.1.1 on 2022-10-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_emailvisitor_name_alter_emailvisitor_phonevisitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailvisitor',
            old_name='name',
            new_name='namevisitor',
        ),
    ]
