# Generated by Django 4.1.1 on 2022-10-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_description_agent_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='contry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.country'),
        ),
    ]
