# Generated by Django 4.1.1 on 2022-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_nationality_contry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to='User_photo'),
        ),
    ]
