# Generated by Django 4.1.1 on 2022-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infopiece',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='social_link',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
